#pragma once

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <string>
#include <algorithm>
#include <vector>
#include <esp_wifi.h>
#include <esp_netif.h>
#include <esp_http_server.h>
#include <esp_ota_ops.h>
#include <esp_system.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include "StatusLedManager.h"
#include "config/Config.h"

// Config web page embedded from src/config.min.html (generated by
// scripts/minify_html.py before each build).
extern const uint8_t config_html_start[] asm("_binary_config_min_html_start");
extern const uint8_t config_html_end[]   asm("_binary_config_min_html_end");

class ConfigManager; // forward declaration -- full definition in ConfigManager.h

// ---------------------------------------------------------------------------
// WebUIConfigManager -- WiFi AP setup and HTTP web UI routes.
// Reads/writes config state via ConfigManager.
// ---------------------------------------------------------------------------

class WebUIConfigManager {
public:
  void begin(StatusLedManager* led, const char* firmwareVersion);

  // bondList: known HID peers offered as target options in the web UI.
  // batVoltageMv / batPercent: battery snapshot for display (-1 = unavailable).
  void beginConfigAP(ConfigManager* cm,
                     const std::vector<std::string>& bondList,
                     int batVoltageMv = -1, int batPercent = -1);
  void handleClient() {}
  void endConfigAP();

  bool isExitRequested() const  { return _exitConfig; }
  void setExitRequested(bool v) { _exitConfig = v; }

private:
  StatusLedManager* _led          = nullptr;
  bool              _exitConfig   = false;
  char              _firmwareVersion[32] = {};
  ConfigManager*    _cm           = nullptr;
  std::vector<std::string> _bondList;
  int               _batVoltageMv = -1;
  int               _batPercent   = -1;
  httpd_handle_t    _server       = nullptr;
  esp_netif_t*      _apNetif      = nullptr;
  const char*       _apSsid       = "RemoteKeyboard-Config";
  const char*       _apPswd       = "remotekeyboard";

  static void        _strReplace(std::string& s, const std::string& from, const std::string& to);
  static void        _strTrim(std::string& s);
  static std::string _urlDecode(const char* src, size_t len);
  static std::string _formParam(const char* body, const char* name);
  static bool        _readBody(httpd_req_t* req, std::string& out);

  static esp_err_t _s_root(httpd_req_t* req);
  static esp_err_t _s_save(httpd_req_t* req);
  static esp_err_t _s_clearbonds(httpd_req_t* req);
  static esp_err_t _s_update(httpd_req_t* req);

  void _handleRoot(httpd_req_t* req);
  void _handleSave(httpd_req_t* req);
  void _handleClearBonds(httpd_req_t* req);
  void _handleUpdate(httpd_req_t* req);
};
