#pragma once

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <string>
#include <algorithm>
#include <vector>
#include <esp_wifi.h>
#include <esp_netif.h>
#include <esp_http_server.h>
#include <esp_ota_ops.h>
#include <esp_system.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include "StatusLedManager.h"
#include "PersistenceManager.h"

// Config web page embedded from src/config.min.html (generated by
// scripts/minify_html.py before each build).
extern const uint8_t config_html_start[] asm("_binary_config_min_html_start");
extern const uint8_t config_html_end[]   asm("_binary_config_min_html_end");

// ---------------------------------------------------------------------------
// WebUIConfigManager -- manages the config WiFi Access Point and the web
// server routes.  Reads/writes persistent settings via PersistenceManager.
// ---------------------------------------------------------------------------

class WebUIConfigManager {
public:
  // Inject the StatusLedManager so web handlers can signal progress via LED,
  // and the firmware version string to display in the web config UI.
  void begin(StatusLedManager* led, const char* firmwareVersion);

  // Bond list is passed here (collected from BLEManager before BLE is stopped)
  // so the web UI can offer known peers as HID target options.
  // Battery voltage (mV) and percentage are passed for display in the web UI;
  // pass -1 for either to indicate no reading is available.
  // A pointer to the PersistenceManager is required to read/write settings.
  void beginConfigAP(PersistenceManager* pm,
                     const std::vector<std::string>& bondList,
                     int batVoltageMv = -1, int batPercent = -1);
  void handleClient() {}
  void endConfigAP();

  bool isExitRequested() const  { return _exitConfig; }
  void setExitRequested(bool v) { _exitConfig = v; }

private:
  StatusLedManager*  _led          = nullptr;
  bool               _exitConfig   = false;
  char               _firmwareVersion[32] = {};
  PersistenceManager* _pm          = nullptr;
  std::vector<std::string> _bondList;    // populated at AP start
  int                _batVoltageMv  = -1; // battery voltage passed at AP start (-1 = unavailable)
  int                _batPercent    = -1; // battery percent passed at AP start (-1 = unavailable)
  httpd_handle_t     _server        = nullptr;
  esp_netif_t*       _apNetif       = nullptr;
  const char*        _apSsid        = "RemoteKeyboard-Config";
  const char*        _apPswd        = "remotekeyboard";

  // ---------------------------------------------------------------------------
  // String helpers
  // ---------------------------------------------------------------------------
  static void        _strReplace(std::string& s, const std::string& from, const std::string& to);
  static void        _strTrim(std::string& s);
  static std::string _urlDecode(const char* src, size_t len);
  static std::string _formParam(const char* body, const char* name);
  static bool        _readBody(httpd_req_t* req, std::string& out);

  // ---------------------------------------------------------------------------
  // Static trampoline handlers (httpd requires plain function pointers)
  // ---------------------------------------------------------------------------
  static esp_err_t _s_root(httpd_req_t* req);
  static esp_err_t _s_save(httpd_req_t* req);
  static esp_err_t _s_clearbonds(httpd_req_t* req);
  static esp_err_t _s_update(httpd_req_t* req);

  // ---------------------------------------------------------------------------
  // Web handler implementations
  // ---------------------------------------------------------------------------
  void _handleRoot(httpd_req_t* req);
  void _handleSave(httpd_req_t* req);
  void _handleClearBonds(httpd_req_t* req);
  void _handleUpdate(httpd_req_t* req);
};
